### ISSUE TITLE
Figure out mobile strategy for Nav Pills 

### ISSUE THREAD

**Issue by marcamillion** [marcamillion/10pointplan#10]
As it stands right now, it seems fine with just 3 or 4 items in the `nav pills` navigation on mobile.

It looks like this:

![photo feb 21 3 01 31 am](https://cloud.githubusercontent.com/assets/137772/13201624/23ac7846-d848-11e5-8194-ebeb4178e842.png)

But as we add more pages, it is going to begin to break. So we need to figure out a solution.

**Comment by shawnmclean** [comment]
We could use the `navbar` class that should resize to a mobile friendly dropdown navigation: http://getbootstrap.com/components/#navbar

Another option if we're sticking with pills: http://patrickdesjardins.com/blog/modifying-bootstrap-tab-control-for-extra-small-device

**Comment by marcamillion** [comment]
Ok let's try using the `navbar` class and see how that looks. If it resizes it in a responsive, mobile-friendly, way...then that's most ideal. We don't NEED to stick to pills. It just needs to look good. The styling was done for those pills though, so we need to keep the same look and feel (particular the colors for the branding). So play around with it and let me know your thoughts.

**Comment by marcamillion** [comment]
@djuvane Have any thoughts on Shawn's suggestion?

**Comment by djuvane** [comment]
I think we go with the drop down option.

On Sun, Feb 21, 2016, 3:23 AM Shawn Mclean <notifications@github.com> wrote:

> We could use the navbar class that should resize to a mobile friendly
> dropdown navigation: http://getbootstrap.com/components/#navbar
>
> Another option if we're sticking with pills:
> http://patrickdesjardins.com/blog/modifying-bootstrap-tab-control-for-extra-small-device
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/marcamillion/10pointplan/issues/10#issuecomment-186774981>
> .
>
-- 

--
Djuvane Browne
Team Leader
djuvane@onegreatstudio.com
JA - (876) 879 9000
USA - (786) 467 7020

**Comment by marcamillion** [comment]
Ok that sounds good to me.

On Sunday, February 21, 2016, Djuvane Browne <notifications@github.com>
wrote:

> I think we go with the drop down option.
>
> On Sun, Feb 21, 2016, 3:23 AM Shawn Mclean <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > We could use the navbar class that should resize to a mobile friendly
> > dropdown navigation: http://getbootstrap.com/components/#navbar
> >
> > Another option if we're sticking with pills:
> >
> http://patrickdesjardins.com/blog/modifying-bootstrap-tab-control-for-extra-small-device
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/marcamillion/10pointplan/issues/10#issuecomment-186774981
> >
> > .
> >
> --
>
> --
> Djuvane Browne
> Team Leader
> djuvane@onegreatstudio.com
> <javascript:_e(%7B%7D,'cvml','djuvane@onegreatstudio.com');>
> JA - (876) 879 9000
> USA - (786) 467 7020
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/marcamillion/10pointplan/issues/10#issuecomment-186807365>
> .
>


-- 
Marc Gayle
www.marcgayle.com
www.twitter.com/marcgayle

**Comment by marcamillion** [comment]
We need to address this STAT gents!

On Sunday, February 21, 2016, Marc Gayle <marcamillion@gmail.com> wrote:

> Ok that sounds good to me.
>
> On Sunday, February 21, 2016, Djuvane Browne <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> I think we go with the drop down option.
>>
>> On Sun, Feb 21, 2016, 3:23 AM Shawn Mclean <notifications@github.com>
>> wrote:
>>
>> > We could use the navbar class that should resize to a mobile friendly
>> > dropdown navigation: http://getbootstrap.com/components/#navbar
>> >
>> > Another option if we're sticking with pills:
>> >
>> http://patrickdesjardins.com/blog/modifying-bootstrap-tab-control-for-extra-small-device
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <
>> https://github.com/marcamillion/10pointplan/issues/10#issuecomment-186774981
>> >
>> > .
>> >
>> --
>>
>> --
>> Djuvane Browne
>> Team Leader
>> djuvane@onegreatstudio.com
>> JA - (876) 879 9000
>> USA - (786) 467 7020
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/marcamillion/10pointplan/issues/10#issuecomment-186807365>
>> .
>>
>
>
> --
> Marc Gayle
> www.marcgayle.com
> www.twitter.com/marcgayle
>


-- 
Marc Gayle
www.marcgayle.com
www.twitter.com/marcgayle

**Comment by marcamillion** [comment]
@luechenchris or @djuvane We have commented out the navigation in the latest push to `gh-pages`. So when you guys fix it, make sure you fix it on all pages and uncomment the old navigation.

Also make sure the correct item has the class `active` on the right page. i.e. the `Security` `li` tag has `active` on `security.html`, etc.

**Comment by shawnmclean** [comment]
New change looks awesome!
