### ISSUE TITLE
Add 'Security' 10 Steps

### ISSUE THREAD

**Issue by marcamillion** [marcamillion/10pointplan#2]
Per [the Manifesto](http://jamaicalabourparty.com/content/jlp-manifesto-2016) page 19, please add those 10 'Steps to Safety and Security' to a new page called 'security.html'. 

The workflow can be as follows:
- Fork `gh-pages` branch into a new branch say `security-content`
- Copy `ict.html`
- Rename it `security.html`
- Update the 'nav-pill' on all of the pages to add 'Security' to the list of navigation beside 'General, ICT, etc.'. **Make sure this is done on ALL pages**.
- Replace the copy for each of the 10 points with those in the manifesto (page 19)
- Write a suitable heading for each
- Submit PR to merge into `gh-pages`
- ????
- Profit

**Comment by shawnmclean** [comment]
Branch: `content-security`
